import { Component, OnInit } from '@angular/core';
import { FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService, LoginRequest } from '../../../core/services/auth.service';
import { NotificationService } from '../../../core/services/notification.service';
import { MatSnackBar } from '@angular/material/snack-bar';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent implements OnInit {
  loginForm: FormGroup;
  isLoading = false;
  hidePassword = true;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router,
    private notificationService: NotificationService,
    private snackBar: MatSnackBar
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.required, Validators.email]],
      password: ['', [Validators.required]]
    });
  }

  ngOnInit(): void {
  }

  onSubmit(): void {
    if (this.loginForm.valid) {
      this.isLoading = true;
      const loginData: LoginRequest = this.loginForm.value;
      console.log('Login data being sent:', loginData);
      
      this.authService.login(loginData).subscribe({
        next: (response) => {
          console.log('Login success callback triggered, response:', response);
          this.createWelcomeNotification(response.userId);
          this.router.navigate(['/']);
        },
        error: (error) => {
          console.log('Login error callback triggered, error:', error);
          this.isLoading = false;
          console.error('Login error:', error);
        }
      });
    }
  }

  private createWelcomeNotification(userId: number): void {
    const welcomeNotification = {
      id: 0, // Will be generated by backend
      userId: userId,
      type: 'WELCOME' as const,
      title: 'Welcome Back!',
      message: 'You have successfully logged in to RevHire.',
      isRead: false,
      createdAt: new Date().toISOString()
    };
    
    this.notificationService.createNotification(welcomeNotification).subscribe({
      next: () => {
        console.log('Welcome notification created successfully');
      },
      error: (error) => {
        console.error('Error creating welcome notification:', error);
        // Fallback: Show snackbar notification
        this.snackBar.open('Welcome Back! You have successfully logged in to RevHire.', 'Close', {
          duration: 5000,
          horizontalPosition: 'center',
          verticalPosition: 'top'
        });
      }
    });
  }

  togglePasswordVisibility(): void {
    this.hidePassword = !this.hidePassword;
  }
}
